spring.application.name=famora

#-----------------
#----DYNAMO_DB----
#-----------------
aws.dynamo.endPoint=https://dynamodb.us-west-2.amazonaws.com
aws.region=us-west-2
aws.dynamo.accessKey=AKIATCKARDSXUHTS53AJ
aws.dynamo.secret=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
